# Assignment: Ionosphere Data Problem

### Dataset Description: 

This radar data was collected by a system in Goose Bay, Labrador. This system consists of a phased array of 16 high-frequency antennas with a total transmitted power on the order of 6.4 kilowatts. See the paper for more details. The targets were free electrons in the ionosphere. "Good" radar returns are those showing evidence of some type of structure in the ionosphere. "Bad" returns are those that do not; their signals pass through the ionosphere.

Received signals were processed using an autocorrelation function whose arguments are the time of a pulse and the pulse number. There were 17 pulse numbers for the Goose Bay system. Instances in this databse are described by 2 attributes per pulse number, corresponding to the complex values returned by the function resulting from the complex electromagnetic signal.

### Attribute Information:

- All 34 are continuous
- The 35th attribute is either "good" or "bad" according to the definition summarized above. This is a binary classification task.

 <br><br>

<table border="1"  cellpadding="6">
	<tbody>
        <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Data Set Characteristics:&nbsp;&nbsp;</b></p></td>
		<td><p class="normal">Multivariate</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Instances:</b></p></td>
		<td><p class="normal">351</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Area:</b></p></td>
		<td><p class="normal">Physical</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">
    <tbody>
        <tr>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Attribute Characteristics:</b></p></td>
            <td><p class="normal">Integer,Real</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Number of Attributes:</b></p></td>
            <td><p class="normal">34</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Date Donated</b></p></td>
            <td><p class="normal">N/A</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">	
    <tbody>
    <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Associated Tasks:</b></p></td>
		<td><p class="normal">Classification</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Missing Values?</b></p></td>
		<td><p class="normal">N/A</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Web Hits:</b></p></td>
		<td><p class="normal">N/A</p></td>
	</tr>
    </tbody>
    </table>

### WORKFLOW :
- Load Data
- Check Missing Values ( If Exist ; Fill each record with mean of its feature ) or any usless column.
- Shuffle the data if needed.
- Standardized the Input Variables. **Hint**: Centeralized the data
- Split into 60 and 40 ratio.
- Encode labels.
- Model : 1 hidden layers including 16 unit.
- Compilation Step (Note : Its a Binary problem , select loss , metrics according to it)
- Train the Model with Epochs (100).
- If the model gets overfit tune your model by changing the units , No. of layers , epochs , add dropout layer or add Regularizer according to the need .
- Prediction should be > **92%**
- Evaluation Step
- Prediction

# Load Data:
[Click Here to Download DataSet](https://github.com/ramsha275/ML_Datasets/blob/main/ionosphere_data.csv)

In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from tensorflow.keras import models, layers, optimizers

In [4]:
df = pd.read_csv('../ionosphere_data.csv')

In [5]:
df

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307,g
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712,g
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577,g
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243,g
350,1,0,0.84710,0.13533,0.73638,-0.06151,0.87873,0.08260,0.88928,-0.09139,...,-0.15114,0.81147,-0.04822,0.78207,-0.00703,0.75747,-0.06678,0.85764,-0.06151,g

In [6]:
df.isnull().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   feature1   351 non-null    int64
 1   feature2   351 non-null    int64
 2   feature3   351 non-null    float64
 3   feature4   351 non-null    float64
 4   feature5   351 non-null    float64
 5   feature6   351 non-null    float64
 6   feature7   351 non-null    float64
 7   feature8   351 non-null    float64
 8   feature9   351 non-null    float64
 9   feature10  351 non-null    float64
 10  feature11  351 non-null    float64
 11  feature12  351 non-null    float64
 12  feature13  351 non-null    float64
 13  feature14  351 non-null    float64
 14  feature15  351 non-null    float64
 15  feature16  351 non-null    float64
 16  feature17  351 non-null    float64
 17  feature18  351 non-null    float64
 18  feature19  351 non-null    float64
 19  feature20  351 non-null    float64
 20  feature21  351 non-null    float64
 21  feature22  351 non-null    float64
 22  feature23  351 non-null    float64
 23  feature24  351 non-null    float64
 24  feature25  351 non-null    float64
 25  feature26  351 non-null    float64
 26  feature27  351 non-null    float64
 27  feature28  351 non-null    float64
 28  feature29  351 non-null    float64
 29  feature30  351 non-null    float64
 30  feature31  351 non-null    float64
 31  feature32  351 non-null    float64
 32  feature33  351 non-null    float64
 33  feature34  351 non-null    float64
 34  label      351 non-null    object
dtypes: float64(32), int64(2), object(1)
memory usage: 96.1+ KB

In [8]:
df.duplicated().any()

True

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df['label'] = df['label'].map({'g':1,'b':0})

In [11]:
df.sample(5)

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
17,0,0,0.00000,0.00000,-1.00000,-1.00000,1.00000,1.00000,-1.00000,1.00000,...,1.00000,1.00000,-1.00000,-1.00000,1.00000,-1.00000,-1.00000,1.00000,-1.00000,0
329,1,0,0.88110,0.00000,0.94817,-0.02744,0.93598,-0.01220,0.90244,0.01829,...,0.04878,0.89666,0.02226,0.90854,0.00915,1.00000,0.05488,0.97561,-0.01220,1
62,1,0,1.00000,0.16801,0.99352,0.16334,0.94616,0.33347,0.91759,0.22610,...,0.55236,0.43317,0.69129,0.35684,0.76147,0.33921,0.66844,0.22101,0.78685,1
43,1,0,-0.64286,-1.00000,1.00000,0.82857,1.00000,-1.00000,1.00000,-0.23393,...,0.85714,1.00000,1.00000,1.00000,-1.00000,1.00000,-1.00000,1.00000,-1.00000,0
315,1,0,0.88085,0.35232,0.68389,0.65128,0.34816,0.79784,0.05832,0.90842,...,-0.75533,0.17041,-0.71504,0.40675,-0.57649,0.56626,-0.36765,0.62765,-0.13305,1

In [12]:
data = df.iloc[:,:-1]
label = df.iloc[:,-1]

In [13]:
data.shape

(350, 34)

In [14]:
label.shape

(350,)

In [15]:
x_train=data.sample(frac=0.6,random_state=1)
x_test=data.sample(frac=0.4,random_state=1)
y_train=label.sample(frac=0.6,random_state=1)
y_test=label.sample(frac=0.4,random_state=1)

In [16]:
x_train=np.asarray(x_train).astype("float32")
x_test=np.asarray(x_test).astype("float32")

In [18]:
model = models.Sequential()
model.add(layers.Dense(16,activation="relu",input_shape=(x_train.shape[1],)))
model.add(layers.Dense(1,activation="sigmoid"))
model.compile(optimizer="rmsprop",loss="binary_crossentropy",metrics=["accuracy"])

In [19]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_2 (Dense)              (None, 16)                560
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 17
=================================================================
Total params: 577
Trainable params: 577
Non-trainable params: 0
_________________________________________________________________

In [20]:
history = model.fit(x_train,y_train,epochs=40,batch_size=1,verbose=1)

Epoch 1/40
210/210 [==============================] - 0s 2ms/sample - loss: 0.5979 - acc: 0.6905
Epoch 2/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.5057 - acc: 0.7333
Epoch 3/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.4428 - acc: 0.8190
Epoch 4/40
210/210 [==============================] - 0s 2ms/sample - loss: 0.3821 - acc: 0.8429
Epoch 5/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.3224 - acc: 0.9000
Epoch 6/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.2780 - acc: 0.9048
Epoch 7/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.2575 - acc: 0.9190
Epoch 8/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.2271 - acc: 0.9381
Epoch 9/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.2044 - acc: 0.9524
Epoch 10/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1936 - acc: 0.9476
Epoch 11/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1786 - acc: 0.9619
Epoch 12/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1621 - acc: 0.9619
Epoch 13/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1599 - acc: 0.9524
Epoch 14/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1547 - acc: 0.9619
Epoch 15/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1446 - acc: 0.9667
Epoch 16/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1407 - acc: 0.9619
Epoch 17/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1400 - acc: 0.9571
Epoch 18/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1343 - acc: 0.9667
Epoch 19/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1275 - acc: 0.9667
Epoch 20/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1288 - acc: 0.9667
Epoch 21/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1222 - acc: 0.9714
Epoch 22/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1199 - acc: 0.9714
Epoch 23/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1286 - acc: 0.9667
Epoch 24/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1067 - acc: 0.9762
Epoch 25/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1165 - acc: 0.9714
Epoch 26/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1039 - acc: 0.9714
Epoch 27/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1075 - acc: 0.9714
Epoch 28/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1120 - acc: 0.9714
Epoch 29/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1025 - acc: 0.9762
Epoch 30/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1018 - acc: 0.9714
Epoch 31/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.1007 - acc: 0.9714
Epoch 32/40
210/210 [==============================] - 0s 2ms/sample - loss: 0.0989 - acc: 0.9762
Epoch 33/40
210/210 [==============================] - 0s 2ms/sample - loss: 0.0988 - acc: 0.9762
Epoch 34/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.0951 - acc: 0.9762
Epoch 35/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.0932 - acc: 0.9762
Epoch 36/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.0928 - acc: 0.9762
Epoch 37/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.0897 - acc: 0.9714
Epoch 38/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.0890 - acc: 0.9762
Epoch 39/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.0922 - acc: 0.9762
Epoch 40/40
210/210 [==============================] - 0s 1ms/sample - loss: 0.0865 - acc: 0.9762

In [21]:
model.evaluate(x_test, y_test)

140/140 [==============================] - 0s 221us/sample - loss: 0.0755 - acc: 0.9786

[0.07554022398378168, 0.9785714]

In [22]:
pred = model.predict(x_test)
pred[1]

array([0.9723778], dtype=float32)